# Generated by Django 4.2.2 on 2023-08-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('F', 'Fashions'), ('J', 'jewellery')], default='E', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('E', 'Electronics'), ('F', 'Fashions'), ('J', 'jewellery')], default='p', max_length=2),
            preserve_default=False,
        ),
    ]
